server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    hostname: localhost
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: mycj-student-service
          uri: lb://mycj-student-service
          predicates:
              - Path=/estudiantes/**
        - id: lmhp-estudiante-service
          uri: lb://lmhp-estudiante-service
          predicates:
            - Path=/estudiantes/**
        - id: rdcm-curso-service
          uri: lb://rdcm-curso-service
          predicates:
            - Path=/cursos/**
        - id: dmb-matricula-service
          uri: lb://dmb-matricula-service
          predicates:
            - Path=/matriculas/**









