
server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielccanayucra/DAD-2025-I.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: root
      password: 123456